version: '3.8'

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    volumes:
      - ./certs:/certs   
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 --tls --tlscert /certs/server-cert.pem --tlskey /certs/server-key.pem --tlscacert /certs/ca-cert.pem" 
    networks: ["nats"]

networks:
  nats:
    name: nats
